"""only one club per group

Revision ID: 07b12ddafbac
Revises: 2a08009f229c
Create Date: 2022-02-19 16:50:09.317741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b12ddafbac'
down_revision = '2a08009f229c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'club', ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'club', type_='unique')
    # ### end Alembic commands ###
