"""add poll_id to club

Revision ID: 1b5d3a9ed272
Revises: 07b12ddafbac
Create Date: 2022-02-20 18:42:26.771732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5d3a9ed272'
down_revision = '07b12ddafbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('poll_msg_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'poll_msg_id')
    # ### end Alembic commands ###
